spring:
  mail:
    host: smtp.qq.com #邮箱服务器地址(其他非qq邮箱服务器地址需要对应修改)
    username: 1185164xxx@qq.com #邮箱地址
    password: acefswcriysxxxxx #授权码
    default-encoding: UTF-8

mail:
  fromMail.addr: 1185164xxx@qq.com  #邮件发送者