spring:
  mail:
    host: smtp.qq.com #邮箱服务器地址(其他非qq邮箱服务器地址需要对应修改)
    username: 1185164xxx@qq.com #邮箱地址
    password: acefswcriysxxxxx #授权码
    default-encoding: UTF-8

  #数据源连接信息
  datasource:
    username: root
    password: admin123
    url: jdbc:mysql://192.168.20.161:3306/study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mail:
  fromMail.addr: 1185164xxx@qq.com  #邮件发送者

mybatis:
  mapper-locations: classpath*:mapper/*.xml